# Site settings
name: A Brief Story of Time
email: zykimmy714@gmail.com
author: Zengyu
url: https://zengyu714.github.io
resume_site: ''
github: https://github.com/zengyu714
baseurl: ''
description: 临事而惧，好谋而成
meta_description: zen
motto: Make lives extraordinary
banner: 学无止境

#permalink: /:categories/:year/:month/:day/:title/
permalink: /:categories/:year/:month/:day/:title/
paginate: 10

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']

github_username: zykimmy714
highlighter: pygments

# Build settings
markdown: kramdown


FB:
  comments :
    provider : disqus
    # duoshuo:
    #     short_name : zengyu714
    disqus :
        short_name : zengyu714

    # facebook :
    #   appid : 123
    #   num_posts: 5
    #   width: 580
    #   colorscheme: light
